add lesson-1-buttons solution
js-tasks-ru/htmlcss-20231027_shuklinvlad pull request #5
Opened 2023-11-16 11:42 UTC by ShuklinVlad

- Добавил решение для задачи Кнопка из 1-й лекции.
- Изменил и добавил цвета из макета в main.css

2023-11-16 11:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-16 23:16 UTC, GSemikozov requested changes

2023-11-16 23:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
не фиксируем

2023-11-16 23:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-bottom: 14px;
слева-справа тоже надо

2023-11-20 16:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-20 16:18 UTC, ShuklinVlad commented on 03-lection1/01-button/button.css
> +    width: 189px;
Убрал фиксированную ширину кнопок

2023-11-20 16:19 UTC, ShuklinVlad commented on 03-lection1/01-button/button.css
> +    padding-bottom: 14px;
Добавил padding справа и слева
нижний тоже сделал 15px

2023-11-20 20:39 UTC, GSemikozov approved these changes

2023-11-20 20:39 UTC, merged